### ISSUE TITLE
Как перенастроить для Docker mysql-client который сменился на mariadb-client?

### ISSUE THREAD

**Issue by devhackerone** [ElisDN/laravel-demo-board#4]
docker-compose logs -f mysql
Attaching to laravel-demo-board_mysql_1
mysql_1          | 2019-12-17 06:59:19+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
mysql_1          | 2019-12-17 06:59:20+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1          | 2019-12-17 06:59:20+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
mysql_1          | 2019-12-17 06:59:21+00:00 [Note] [Entrypoint]: Initializing database files
mysql_1          | 2019-12-17T06:59:21.072792Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1          | 2019-12-17T06:59:21.094272Z 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
mysql_1          | 2019-12-17T06:59:21.834052Z 0 [ERROR] InnoDB: Operating system error number 22 in a file operation.
mysql_1          | 2019-12-17T06:59:21.834181Z 0 [ERROR] InnoDB: Error number 22 means 'Invalid argument'
mysql_1          | 2019-12-17T06:59:21.834220Z 0 [ERROR] InnoDB: File ./ib_logfile101: 'aio write' returned OS error 122. Cannot continue operation
mysql_1          | 2019-12-17T06:59:21.834299Z 0 [ERROR] InnoDB: Cannot continue operation.
mysql_1          | 2019-12-17 07:08:38+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
mysql_1          | 2019-12-17 07:08:38+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1          | 2019-12-17 07:08:38+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.28-1debian9 started.
mysql_1          | 2019-12-17 07:08:38+00:00 [Note] [Entrypoint]: Initializing database files
mysql_1          | 2019-12-17T07:08:38.556856Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1          | 2019-12-17T07:08:38.564331Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
mysql_1          | 2019-12-17T07:08:38.564482Z 0 [ERROR] Aborting
mysql_1          |
laravel-demo-board_mysql_1 exited with code 1

**Comment by devhackerone** [comment]
Решил)))

FROM php:7.1-cli

RUN apt-get update && apt-get install -y libmcrypt-dev **mariadb-client** \
    && docker-php-ext-install mcrypt pdo_mysql pcntl

WORKDIR /var/www

FROM php:7.1-fpm

RUN apt-get update && apt-get install -y libmcrypt-dev **mariadb-client** \
    && docker-php-ext-install mcrypt pdo_mysql

WORKDIR /var/www

mysql:
        image: mysql:5.7
        **command: --innodb_use_native_aio=0**
        volumes:


[laravel-demo-board.zip](https://github.com/ElisDN/laravel-demo-board/files/3971978/laravel-demo-board.zip)

**Comment by oleksandr-roskovynskyi** [comment]
Решил)))

FROM php:7.1-cli

RUN apt-get update && apt-get install -y libmcrypt-dev **mariadb-client** \
    && docker-php-ext-install mcrypt pdo_mysql pcntl

WORKDIR /var/www

FROM php:7.1-fpm

RUN apt-get update && apt-get install -y libmcrypt-dev **mariadb-client** \
    && docker-php-ext-install mcrypt pdo_mysql

WORKDIR /var/www

mysql:
        image: mysql:5.7
        **command: --innodb_use_native_aio=0**
        volumes:

[laravel-demo-board.zip](https://github.com/ElisDN/laravel-demo-board/files/3971986/laravel-demo-board.zip)
